### ISSUE TITLE
Example on dockerhub is not working

### ISSUE THREAD

**Issue by JoyceBabu** [EnigmaCurry/lazy-distro-mirrors#1]
There is a space character after `-d --restart=always \` in the usage section on DockerHub. Due to this, copy pasting the `docker run` command is not working. I tried to create a pull request fixing this, but the issue is not present in the `README.md` file in GitHub.

**Comment by JoyceBabu** [comment]
Also, the docker run command is incorrect on DockerHub. It shows

```
--volume /opt/docker/lazy-distro-mirrors/config:/docker_configurator/
```

instead of

```
--volume /opt/docker/lazy-distro-mirrors/config:/docker_configurator/user
```

**Comment by EnigmaCurry** [comment]
Looks like dockerhub's markdown parser works better these days. Thanks, and sorry for not seeing this ages ago.
